### ISSUE TITLE
Latest Registry Address is Wrong

### ISSUE THREAD

**Issue by johnnyshankman** [tokenbound/sdk#1]
States: `0x1472D0f5c6c151df96352Ec271B8dF1093370A7A`

Seems the most recent is: `0x02101dfb77fde026414827fdc604ddaf224f0921`

The old one does not concatenate the account address the same way as the EIP https://eips.ethereum.org/EIPS/eip-6551 (head down to examples, then `Registry Implementation`.

https://goerli.etherscan.io/address/0x1472D0f5c6c151df96352Ec271B8dF1093370A7A#code
https://goerli.etherscan.io/address/0x02101dfb77fde026414827fdc604ddaf224f0921#code

**Comment by jaydenwindle** [comment]
Sorry about that! This is fixed in [v0.2.0](https://github.com/tokenbound/sdk/releases/tag/v0.2.0)
