### ISSUE TITLE
[No Media] error on page.

### ISSUE THREAD

**Issue by jacmos3** [tokenbound/sdk#18]
Hello, I am trying using the tokenbound app, but I noticed that it is not supporting so well those NFTs which have Base64 strings instead of an URL for the image on polygon.  
I tried to see other NFT collections which use Base64 strings on Ethereum, and it works fine there. The issue seems to be on Polygon only.

For instance: when I access here
https://tokenbound.org/assets/polygon/0x5f9eb32051ad505a36382ce2a96cc8006349e2fb/17
I see "[No Media]" in the image box, instead it has a media, and for example on opensea it is visibile: 

https://opensea.io/assets/matic/0x5f9eb32051ad505a36382ce2a96cc8006349e2fb/17

Thank you

**Comment by bjfresh** [comment]
Thanks for the heads-up @jacmos3. I'm going to close this and move it into our ticket tracking system for tokenbound.org since it's not SDK-related, but we'll definitely get this sorted.

**Comment by bjfresh** [comment]
@jacmos3 just FYI there's a PR up for this. Should be merged soon.

**Comment by jacmos3** [comment]
wow thank you!! I see it's working now!!
