### ISSUE TITLE
Feature Request: Allow to set a custom RPC url

### ISSUE THREAD

**Issue by sarhugo** [tokenbound/sdk#25]
Hi, I'm trying to call the getNFT method to get the bound token for the account but I got timeouts from the rpc https://matic-mumbai.chainstacklabs.com

It would be great to be able to set a custom RPC url for the client. I know that starting from version 0.3.6 there is a new publicClient parameter that allows to customize it but maybe adding a new parameter for just this prevents all the required imports

**Comment by scammi** [comment]
You can pass a [Signer](https://docs.ethers.org/v5/api/signer/) connected to your specified provider.

https://github.com/tokenbound/sdk/blob/main/packages/sdk/src/TokenboundClient.ts#L116C6-L116C6

**Comment by sarhugo** [comment]
@scammi but for the getNFT method (or deconstructBytecode) it uses the publicClient, not the signer

**Comment by fallanic** [comment]
@sarhugo I just started playing with the SDK myself, so apologies if my advice is off, but with `Viem` you can pass a custom RPC URL as a parameter of the HTTP stransport, as described here: https://viem.sh/docs/clients/transports/http.html#usage

**Comment by bjfresh** [comment]
@sarhugo good catch on the new publicClient parameter. This was added specifically to enable testing, but I can see how surfacing configurable transport url for publicClient could be useful. This is straightforward enough to add and I have a local implementation, but I'd want to do some additional testing. If I don't encounter issues this may make it into the next release.

**Comment by bjfresh** [comment]
Update: this is live as of v0.3.8
