### ISSUE TITLE
Add support for custom salt input

### ISSUE THREAD

**Issue by ilikesymmetry** [tokenbound/sdk#44]
Currently, the SDK defaults salts to `'0'` in `getAccount`, `createAccount`, and `prepareCreateAccount`. While this default is convenient, it is possible developers will want to decide their own salts. The proposed change is to add an optional argument to these functions to enable salt customization while preserving the `'0'` default value.

**Comment by bjfresh** [comment]
@ilikesymmetry this is in the works for the next release of the SDK. Look for it shortly!
